### PR TITLE
Add logo to the project

### PR DESCRIPTION
**Pull request by cristianovitorino**
- Favicon
- Small logo, dark and light version
- Medium logo, dark and light version
- Large logo, dark and light version
- Source SVG

### CODE REVIEW

**Comment by fosskers** [comment]
Honest question: is it better to have a transparent background (the inside) for the icons?

**Comment by cristianovitorino** [comment]
> Thank you!

Glad to help : )

> Honest question: is it better to have a transparent background (the inside) for the icons?

I think it's possible, but I need more time, take it to another program. I'll see what I can do. I'll PR again why it's ready.

**Comment by cristianovitorino** [comment]
Done!

**Comment by fosskers** [comment]
Thank you! I see that you changed the favicons, probably to have their features more visible despite their small size, eh?

Could you also elaborate about the license that was added? I'm fine with having it, I'd just like to understand it.

**Comment by cristianovitorino** [comment]
> Thank you! I see that you changed the favicons, probably to have their features more visible despite their small size, eh?

Yes. No changes there tho, they were always like that, I just made the middle transparent. I've adapted them so they are readable, because of their small size. If you want I can make just a tiny version of the normal logo, but due to its details, it will not be as readable. Your choice.

> Could you also elaborate about the license that was added? I'm fine with having it, I'd just like to understand it.

It's 100% compatible with Aura's GLPv3. It just protects me as the author of the artwork while being in the same license realm as the software it's being attached to, the same way GPLv3 protects the code you wrote. CC is common practice with artwork.

[Here](https://creativecommons.org/licenses/by-sa/4.0/), more about the license.
And [here](https://www.fsf.org/blogs/licensing/creative-commons-by-sa-4-0-declared-one-way-compatible-with-gnu-gpl-version-3), about the compatibility with GPLv3.

**Comment by fosskers** [comment]
Thank you very much! I'll be adding this to the README immediately. Once I start work on Aura's website, I'll use it there too.

Hm, perhaps I should also alter `aura -V` to provide a text version of the new logo :)

**Comment by cristianovitorino** [comment]
> Thank you very much! I'll be adding this to the README immediately. Once I start work on Aura's website, I'll use it there too.
> 
> Hm, perhaps I should also alter `aura -V` to provide a text version of the new logo :)

Awesome! Was fun working on the project! If you need modifications or need something for your website now or in the future, just gimme a shout.

**Comment by cristianovitorino** [comment]
@fosskers For some reason, the _SVG_ source file didn't go through the PR. I'll do another PR for that.

**Comment by cristianovitorino** [comment]
@fosskers I discovered the problem. Your `.gitignore` has SVG listed on it, I'll disable it for the moment to upload the file OK? You can inspect and revert the `.gitignore` right afterwards.

**Comment by fosskers** [comment]
Ah ha, that was because I had a number of large SVG files locally that were generated during performance testing.

**Comment by cristianovitorino** [comment]
> Ah ha, that was because I had a number of large SVG files locally that were generated during performance testing.

I see. [PR is ready](https://github.com/fosskers/aura/pull/590).

**Pull request merged**
