### PR TITLE
Wide Search

### PR DESCRIPTION
**Pull request by fosskers**
This PR implements a subflag for `-As` that allows it to yield results from the official repos as well.

### TODO

- [x] Confirm exit code details
- [x] Update manpage
- [x] Update CHANGELOG
- [x] Allow multiple search terms for `-As`

### CODE REVIEW

**Comment by ratijas** [comment]
So, ultimately you don't want to do that by default, instead requiring extra typing like subflag `-Ass` etc.?

**Comment by fosskers** [comment]
That's right. In the end, `-A` is for AUR operations primarily. But this extra subflag can fulfill the needs of users like yourself who want both at once.

**Comment by ratijas** [comment]
Idk. It's like both reasonable and not at the same time. What about separate Big Letter flag then?

These indented letters on the right are not used yet:
```
A
B
C
D
    E
    F
    G
h
    I
    J
    K
L
M
    N
O
P
Q
R
S
T
U
V
    W
    X
    Y
    Z
```

Let's say,
- it could be W (stands for Wide as you mentioned earlier) or X (for Cross-worlds), and these two have almost no intersection with lowercase options (only `-x, --unsuppress` for `-A`),
- I don't like Z because it is hard to reach on QWERTY keyboards, 
- Y — I can't think of any mnemonic, and it just doesn't sound right for me.
- N, K, J — same,
- l — don't ever use that one (oh no, it's ell, not big i, by mistake!)
- D, E, G — maybe, but why?

**Comment by fosskers** [comment]
I've altered the long option to `--both`. Any thoughts?

**Pull request merged**
