### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by PandaFoss**
Missing strings in the Spanish language have been completed.
The list of Spanish translators in the README file has been updated.

### CODE REVIEW

**Comment by fosskers** [comment]
Thank you kindly! I'll get this merged in tomorrow morning.

**Comment by fosskers** [comment]
Mental note: Make sure we added you to the man page and `-V` translator list.

**Comment by fosskers** [comment]
Thank you very much!

**Comment by PandaFoss** [comment]
I am learning Haskell right now so I will try to contribute code as soon as I am encouraged! :smile:

**Comment by fosskers** [comment]
Any contribution is welcome :)

**Pull request merged**
