### PR TITLE
Add Bengali (বাংলা) 

### PR DESCRIPTION
**Pull request by saifshahriar**
I don't have any experience with rust. :(
Pleases verify my changes to the rust codes.
Also, I wanted to add two aliases for the language 'Bengali': `'bengali', 'বাংলা'`. Since I couldn't find a way to do so, I kept only the first one.

### CODE REVIEW

**Comment by fosskers** [comment]
Fantastic, thanks a lot for this. I will install a Bengali font and then test this :laughing:

**Comment by saifshahriar** [comment]
Thank you.
Kindly, try it inside **Konsole** terminal as it has the least worst support for Bengali fonts.
Please try them with these settings enabled.

Screenshot_20240913_110126



Here, how it might look with the font [Hind Siliguri](https://fonts.google.com/specimen/Hind+Siliguri) in Konsole:

Screenshot_20240913_105651

Here is how it might look with a Sans version of a Bengali Monospace font Mitra (not Mitra Mono. The monospace variant does not render spaces properly around Bengali fonts):

Screenshot_20240913_110206




Both has a good vowel support for Bengali with the Brahmic Script support turned on. But the spacing is butchered.




Here is how it might look in a minimal terminal like st (JetBrainsMono + Mitra Mono):

Screenshot_20240913_110459


It has good spacing, but no support for Brahmic Script, so the vowels are out of place.

Bengali script is kind of complex, even more than Devanagri/Hindi or Arabic. So, the devs are not interested. Maybe someday we might have an Aura GUI or properly supported terminals.


This is the best font that I have gotten to work with Konsole so far. I don't no how I have this variant in my system. You can find the font [here](https://www.omicronlab.com/bangla-fonts.html), not sure about the exact variant tough.

Screenshot_20240913_113620

**Comment by fosskers** [comment]
Thanks for those screenshots. I'm going to try it on https://wezfurlong.org/wezterm/ , the terminal I've been using recently.

**Comment by fosskers** [comment]
bengali

Looks good to me.

**Comment by fosskers** [comment]
Thanks again!

**Pull request merged**
