### PR TITLE
Italian translation for all available strings

### PR DESCRIPTION
**Pull request by noxgeek**

### CODE REVIEW

**Comment by fosskers** [comment]
Grazie mille! Do you want your name credited in the `-V` message, the README, and the man page?

**Comment by noxgeek** [comment]
Prego! Yes, it would be awesome! My name is Cristian Tentella

**Comment by fosskers** [comment]
I will take care of this tomorrow morning.

**Comment by noxgeek** [comment]
Thank you!

**Comment by fosskers** [comment]
Done!

**Pull request merged**
