### PR TITLE
Rust Port: Part 2 - Dependencies

### PR DESCRIPTION
**Pull request by fosskers**
This PR expands on #671 by rounding off much of the internals of `-A`.

This is a vast improvement over the `Dependencies.hs` Haskell version in both performance and accuracy.

### CODE REVIEW

**Comment by Morganamilo** [comment]
> say compared to what the Haskell does

What does haskell do?

**Comment by fosskers** [comment]
I meant the Haskell version of dep resolution found here: https://github.com/fosskers/aura/blob/master/aura/lib/Aura/Dependencies.hs

**Comment by fosskers** [comment]
And am I right that the AUR site itself support multiple search terms, but the RPC does not?

**Comment by fosskers** [comment]
[This patch](https://lists.archlinux.org/pipermail/aur-dev/2020-July/004937.html) got my hopes up, but I don't see an actual v6 supported here https://gitlab.archlinux.org/archlinux/aurweb/-/blob/master/doc/rpc.txt

**Comment by Morganamilo** [comment]
I've given up on searching for provides because I find my hack to be sufficient to be honest. Do note though that I only do the provider search for targets and missing packages. Doing it at every level is not ideal.

**Comment by Morganamilo** [comment]
Also I pushed a threaded version of aur-fetch using crossbeam https://github.com/Morganamilo/aur-fetch.rs/blob/master/src/fetch.rs#L121

**Comment by fosskers** [comment]
This is now comically fast and handles `provides` correctly.

**Comment by Morganamilo** [comment]
Running your own aur mirror? Seems a bit fragile.

**Comment by fosskers** [comment]
It's just a data mirror, luckily. Otherwise yes, that would be a nightmare.

**Comment by Morganamilo** [comment]
How does it work as a speedup then? Can it handle the traffic of many users?

**Comment by fosskers** [comment]
Because it doesn't use a database and holds all package data in memory, using Rust ref tricks to store `HashMap`s of `&Package` data for each kind of lookup you'd want to do (info, search, and provides).

**Pull request merged**
